### ISSUE TITLE
Schema properties as arrays.

### ISSUE THREAD

**Issue by JamieKitson** [theopensystemslab/digital-planning-data-schemas#255]
In most of the schema, definitions look like this:

            "company": {
              "additionalProperties": false,
              "properties": {
                "name": {
                  "type": "string"
                }
              },

However, in a few places an array is used instead of direct properties:

        "policyRefs": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "text": {
                "type": "string"
              },
              "url": {
                "$ref": "#/definitions/URL"
              }
            },
            "required": [
              "text"
            ],
            "type": "object"
          },
          "type": "array"
        }

Is there a reason for this inconstancy and is it correct?

**Comment by jessicamcinchak** [comment]
Hi Jamie thanks for flagging this - 

In the case of `"policyRefs"` highlighted here, we do indeed support a single question having many associated policy references - therefore `"type": "array"` is correct here. 

Here's an example entry from LDC `responses` where a list of policy refs is used: https://github.com/theopensystemslab/digital-planning-data-schemas/blob/main/examples/prototypeApplication/lawfulDevelopmentCertificate/existing.json#L600-L623

Does this help clarify? Any other `"array"` type definitions in question?
