### ISSUE TITLE
Add proper GeoJSON type

### ISSUE THREAD

**Issue by jessicamcinchak** [theopensystemslab/digital-planning-data-schemas#41]
There isn't a native GeoJSON format available https://github.com/ajv-validator/ajv-formats

Other options:
- https://www.npmjs.com/package/@types/geojson
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/geojson/index.d.ts

**Comment by DafyddLlyr** [comment]
Alternatively - Planning Data use WKT for their application types API which we could align with.

**Comment by jessicamcinchak** [comment]
Planning data's use of WKT is definitely a strong reason to align, but I'm also aware that geojson is our current method of exchange with BOPS, Uniform DMS (it'd be good to gather feedback if the boundary.geojson we send to councils is actually in use?), and our own GIS API / map web components.

Perhaps a good v1 here is actually providing both, similar to how we'll provide "area" in _both_ `metresSquared` & `hectares`?
